title: Terre Pure
author:
  name: pntbr
  email: stephane@pntbr.fr
description: >-
  Un petit outil simple pour présenter et gérer la programmation d'évènements
baseurl: "/programmation"
url: ""
github_username:  pntbr

show_excerpts: true

collections:
  events:
    output: true
    sort_by: nom_animatrice
  animations:
    output: true
    sort_by: nom_animatrice

defaults:
  - scope:
      path: ""
      type: events
    values:
      categorie: stage

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
